POSTER_SIZE = "w780"
BACKDROP_SIZE = "original"
LOGO_SIZE = "original"
PERSON_SIZE = "h632"
STILL_SIZE = "w400"
TMDB_IMAGE_BASE_ORIGINAL = "https://image.tmdb.org/t/p/original"

MEDIA_IMAGE_FOLDERS = ["posters", "backdrops", "logos", "persons", "stills"]
MIN_CACHED_IMAGE_BYTES = 100
PUBLIC_IMAGE_CACHE_TTL_SECONDS = 15

LOGO_PROBE_THUMBNAIL_SIZE = (256, 256)
LOGO_DARK_PIXEL_THRESHOLD = 0.2
LOGO_MIN_AVERAGE_LUMINANCE = 0.32

BACKDROP_PROBE_THUMBNAIL_SIZE = (320, 180)
BACKDROP_MIN_WIDTH = 1920
BACKDROP_PREFERRED_MIN_WIDTH = 2560
BACKDROP_WHITE_PIXEL_THRESHOLD = 0.58

TMDB_IMAGE_SIZES_BY_SUBFOLDER = {
    "posters": POSTER_SIZE,
    "backdrops": BACKDROP_SIZE,
    "logos": LOGO_SIZE,
    "persons": PERSON_SIZE,
    "stills": STILL_SIZE,
}
